name: Release package

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: [self-hosted, universe-ci]
    environment: npm
    timeout-minutes: 15
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: bitcoinuniverseio/universe-ci-actions/universe-node-env@e2a4530be8c5d42e23ed7c198300d05d775ddeb0 # v1
      - run: npm run ci
      - run: npm publish --access public --provenance
